version: '3'

services:

    db:
        build: ./.docker/mysql
        container_name: catalog-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=catalog
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
